version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    hostname: api
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 60m
      timeout: 10s
      retries: 3
    networks:
      - backend-network

  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./migrations/20231020175112_create_people.up.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5432/health" ]
      interval: 60m
      timeout: 10s
      retries: 3
    networks:
      - backend-network

volumes:
  postgres_data: {}

networks:
  backend-network:
    name: "backend-network"
    driver: bridge
